### ISSUE TITLE
Added support for TOML frontmatter syntax highlighting in markdown files

### ISSUE THREAD

**Issue by marcobeltempo** [bungcip/better-toml#10]
**Refrences: [VSCode Issue#41650](https://github.com/Microsoft/vscode/issues/41650)**

I've added support for TOML frontmatter in Markdown files. A feature originally requested in vscode.

**Steps to reproduce:**
1. Create a .md file
2. add to the top line
```
+++

+++
```
3. Insert TOML syntax
```toml
title = "TOML Example"
```
@bungcip I would like your feedback on this feature.
You can test it out here [https://github.com/marcobeltempo/vscode-fenced-toml](https://github.com/marcobeltempo/vscode-fenced-toml)

![image](https://user-images.githubusercontent.com/15523758/36160528-65ebab22-10af-11e8-9e0f-9ea4aadd8045.png)

**Comment by bungcip** [comment]
Hi @marcobeltempo, I already test your https://github.com/marcobeltempo/vscode-fenced-toml.
I think this is a good feature to add. In order to integrate this feature, I think you need to remove `#illegal` pattern in `TOML.tmLanguage` because those pattern will eat `+++`  token.

See my pull request for your example: https://github.com/marcobeltempo/vscode-fenced-toml/pull/1.

If you want to create PR to add this feature please clone it from `0.3` branch (https://github.com/bungcip/better-toml/tree/0.3). Current master branch is broken because i am still not finishing my toml parser library :(

Just remove `#illegal` in `TOML.tmLanguage .YAML`, then convert it to `TOML.tmLanguage ` using `tmLanguage` extension (https://github.com/Togusa09/vscode-tmlanguage)

![image](https://user-images.githubusercontent.com/72723/36186985-158df7b8-1175-11e8-92b1-18ee919f7db2.png)

I happy to waiting your PR :)

**Comment by marcobeltempo** [comment]
@bungcip Thank you for taking the time to review it and submit a pr!
I will be submitting a pull request to 0.3 branch shortly

**Comment by marcobeltempo** [comment]
@bungcip do you suggest keeping the code block rule separate in a `codeblock.tmLanguage` file or integrate it within the existing `TOML.tmLanguage` file?

**Comment by bungcip** [comment]
I think its better to separate it.

**Comment by bungcip** [comment]
new version of better-toml released with this feature.
