### ISSUE TITLE
when can we expect the next release?

### ISSUE THREAD

**Issue by softprops** [bungcip/better-toml#16]
👋 @bungcip. Great vscode extension! 

I was just wondering if this project was still active and if so when we can expect the next release? There have been a lot of [changes since the `0.3.2` release](https://github.com/bungcip/better-toml/compare/0.3.2..master) that remove the [urge to write a toml server myself](https://twitter.com/softprops/status/1057137786682261505).  I was specifically looking for a way to provide a better editing experience of toml configuration files with json schema support. What's in master in this repo seems to do just that. Is this something you're expecting to release soon or as this project gone into maintenance mode?

**Comment by bungcip** [comment]
Hi @softprops, 
`better-toml` still maintained, however due to my IRL works, the progress has been very slow T_T;
my current plan is to change `better-toml` to use a new toml parser library which more suitable for IDE usage.  Currently `better-toml` use `toml-node` to parse toml code but this library has many limitation to support IDE usage. 
Thats why I have been focusing to finishing my [toml parser library, degurechaff](https://github.com/bungcip/degurechaff). 

I think we need a new toml parser library in javascript/typescript before adding more feature to `better-toml`.  I will gladdy throw away degurechaff and use that library if someone created a better & more powerfull toml parser in javascript/typescript :)

**Comment by softprops** [comment]
cool. cool. context is I'm coming from rustlang but now just getting into the vscode IDE space. Something I found missing in the space was autocomplete for Cargo.toml files ( the config file for cargo, the workflow tool for rust ). I dug a bit with snippets and found them to be a little limited which brought me to the language server idea. I didn't see a toml language server listed [here](https://microsoft.github.io/language-server-protocol/implementors/servers/) so I said to myself. "I know I'll write one" but then I found this repo and was like... "maybe not" :) 

I was going to write one in rust ( following some patterns I found [rust language server](https://github.com/rust-lang-nursery/rls) and have the typescript code be the client in vscode. Rust has a pretty good toml parsing library but I don't have much experience with vscode extensions ( or language servers in general ) so I don't know what a good fit looks like. 

In any case let me know. I may just write one for the exercise in learning. I looked at what yours was doing and its *100%* what I'm looking for. I see its validating with json schemas and even have an example for rust's Cargo.toml files! I dont want to re-work what already seems to be work in flight so I just wanted to check in and see how progress was going :)
