### ISSUE TITLE
Delay when saving

### ISSUE THREAD

**Issue by gswalden** [bungcip/better-toml#4]
I noticed a 1-2 second delay when saving .toml files with this extension active. Is this a common issue? What is happening in the background?

Environment:
Better TOML 0.2.0
VS Code 1.9.1
macOS 10.12.3

**Comment by bungcip** [comment]
Hi @gswalden, thanks for using `better-toml`.

Unfortunately I cannot reproduce the issue on my machine, saving `.toml` is basically instant, even on my low spec notebook. I am using windows 10 tough. Are you sure the delay caused by `better-toml` extension?
Can you try to disable other extension and leave `better-toml` alone?

**Comment by gswalden** [comment]
Since my initial post, I've restarted a few times and closed a few VS Code windows. Not seeing the delay anymore, so I'll place the blame on some of our larger repos bogging down resources. Thanks!
